PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wdref: <http://www.wikidata.org/reference/>

SELECT (?numOfStatements AS ?num) WHERE{
SELECT  DISTINCT ?refnode (COUNT(?item) AS ?numOfStatements) WHERE{
        ?item a wikibase:Statement.
        ?item prov:wasDerivedFrom ?refnode.
}GROUP BY ?refnode HAVING(?numOfStatements >= 2)
}

