PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wdref: <http://www.wikidata.org/reference/>
SELECT (COUNT(?refnode) AS ?count) WHERE{
SELECT DISTINCT (COUNT(?item) AS ?items) ?refnode WHERE{
        ?item a wikibase:Statement.
        ?item prov:wasDerivedFrom ?refnode.
}GROUP BY ?refnode HAVING (?items >= 2)
}