PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wdref: <http://www.wikidata.org/reference/>
SELECT (COUNT(?refnode) AS ?count) WHERE{
SELECT DISTINCT (COUNT(?item) AS ?items) ?refnode WHERE{
        ?item a wikibase:Statement.
        ?item prov:wasDerivedFrom ?refnode.
}GROUP BY ?refnode HAVING (?items >= 2)
}
#SELECT (COUNT(?refnode) AS ?refnodecount)  WHERE{
#SELECT * WHERE{ ?item prov:wasDerivedFrom wdref:0dd0a3ca0c59f04441b812145e2be725f4f219bb}
#DESCRIBE wdref:0dd0a3ca0c59f04441b812145e2be725f4f219bb
#	?item a wikibase:Statement;
#	?item prov:wasDerivedFrom ?refnode.
#}
#}HAVING (?items > 2)
