SELECT DISTINCT ?item ?itemLabel WHERE
{ 
  ?item wdt:P31 wd:Q16695773.
  ?sitelink schema:about ?item .
  ?sitelink schema:isPartOf [ wikibase:wikiGroup "wikidata" ] .
  MINUS
  {
    ?item rdfs:label ?label.
    FILTER (CONTAINS(str(?label), "Wikipedia:WikiProject"))
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
